### ISSUE TITLE
Add Support for Dart Language

### ISSUE THREAD

**Issue by abakermi** [LyonSyonII/run#9]
Addition of Dart language  particularly for those working with Flutter. Could we explore the feasibility of integrating `Dart`, considering its growing popularity and utility in mobile and web development?

**Comment by LyonSyonII** [comment]
Thank you for opening this issue!

Could you please look at the newly added [Contribution Guide](https://github.com/LyonSyonII/run/blob/main/CONTRIBUTE.md)?

**Comment by abakermi** [comment]
@LyonSyonII I will add PR
